#pragma once

#ifndef _MessageHandler_15B_2010_h
    #define _MessageHandler_15B_2010_h

#include <cstdint>

#include "../../../IMessageHandler.hpp"
#include "../../Structs/CAN_15B_2010.h"
#include "../../../ImmediateSignal.hpp"
#include "../../../FeedbackSignal.hpp"

class MessageHandler_15B_2010 : public IMessageHandler<MessageHandler_15B_2010>
{
    private:
        ImmediateSignalCallback _immediateSignalCallback = nullptr;
        FeedbackSignalCallback _feedbackSignalCallback = nullptr;

        BusMessage message
        {
            .id = 0x15B,
            .command = 0,
            .data = {0},
            .dataLength = 8,
            .protocol = ProtocolType::AEE2010,
            .periodicityMs = 1000,
            .offsetMs = 130,
            .isActive = false
        };

    public:
        static constexpr uint32_t MessageId = 0x15B;

        void SetImmediateSignalCallback(ImmediateSignalCallback immediateSignalCallback) { _immediateSignalCallback = immediateSignalCallback; }
        void SetFeedbackSignalCallback(FeedbackSignalCallback feedbackSignalCallback) { _feedbackSignalCallback = feedbackSignalCallback; }

        BusMessage Generate(CarState* carState)
        {
            // this is generated by the NAC when the user changes the profile settings
            return message;
        }

        void Parse(CarState* carState, const BusMessage& message)
        {
            bool parametersChanged = false;

            CAN_15B_2010_Byte1Struct languageAndUnits{};
            languageAndUnits.asByte = message.data[0];

            if (languageAndUnits.data.data_valid == 1)
            {
                parametersChanged = carState->LANGUAGE         != languageAndUnits.data.language ||
                                    carState->DISTANCE_UNIT    != languageAndUnits.data.distance_unit ||
                                    carState->CONSUMPTION_UNIT != languageAndUnits.data.consumption_unit;

                carState->LANGUAGE         = languageAndUnits.data.language;
                carState->DISTANCE_UNIT    = languageAndUnits.data.distance_unit;
                carState->CONSUMPTION_UNIT = languageAndUnits.data.consumption_unit;
            }

            CAN_15B_2010_Byte2Struct configuration{};
            configuration.asByte = message.data[1];

            if (configuration.data.data_valid == 1)
            {
                parametersChanged = parametersChanged ||
                                    carState->TEMPERATURE_UNIT != configuration.data.temperature_unit ||
                                    carState->VOLUME_UNIT      != configuration.data.volume_unit ||
                                    carState->AMBIENCE_LEVEL   != configuration.data.ambience_level ||
                                    carState->SOUND_HARMONY    != configuration.data.sound_harmony;

                carState->TEMPERATURE_UNIT = configuration.data.temperature_unit;
                carState->VOLUME_UNIT      = configuration.data.volume_unit;
                carState->AMBIENCE_LEVEL   = configuration.data.ambience_level;
                carState->SOUND_HARMONY    = configuration.data.sound_harmony;
            }

            CAN_15B_2010_Byte3Struct byte3{};
            byte3.asByte = message.data[2];

            carState->CarSettings.Field4.data.ambience_light                 = byte3.data.ambience_light;
            carState->CarSettings.Field4.data.daylight_running_light_enabled = byte3.data.daylight_running_light_enabled;
            carState->CarSettings.Field3.data.adaptive_lights                = byte3.data.adaptive_lights;
            carState->CarSettings.Field4.data.driver_welcome_exterior        = byte3.data.driver_welcome_interior;
            carState->CarSettings.Field2.data.selective_opening_key          = byte3.data.selective_opening_key;
            carState->CarSettings.Field2.data.automatic_parking_brake        = byte3.data.automatic_parking_brake;

            CAN_15B_2010_Byte4Struct byte4{};
            byte4.asByte = message.data[3];

            carState->CarSettings.Field4.data.highway_beam_enabled         = byte4.data.highway_beam_enabled;
            carState->CarSettings.Field3.data.automatic_headlights_enabled = byte4.data.automatic_headlights_enabled;
            carState->CarSettings.Field3.data.follow_me_home_enabled       = byte4.data.follow_me_home_enabled;
            carState->CarSettings.FollowMeHomeTime2010                     = byte4.data.follow_me_home_time; //will be converted when generating the appropriate message

            CAN_15B_2010_Byte5Struct byte5{};
            byte5.asByte = message.data[4];

            carState->CarSettings.Field6.data.aas_status               = byte5.data.aas_enabled ? 3 : 0;
            carState->CarSettings.Field6.data.auto_rear_wiper_enabled  = byte5.data.auto_rear_wiper_enabled;
            carState->CarSettings.ConfigurableButtonFunction2010       = byte5.data.configurable_button_function; //will be converted when generating the appropriate message

            CAN_15B_2010_Byte6Struct byte6{};
            byte6.asByte = message.data[5];

            carState->CarSettings.Field8.data.dsg_enabled = byte6.data.dsg_enabled;

            CAN_15B_2010_Byte7Struct byte7{};
            byte7.asByte = message.data[6];

            carState->CarSettings.ProfileNumber2010      = byte7.data.profile_number; //will be converted when generating the appropriate message
            carState->CarSettings.Field1.data.data_valid = configuration.data.data_valid;

            if (parametersChanged && _feedbackSignalCallback != nullptr)
            {
                carState->SAVE_CONFIG = true;
                _feedbackSignalCallback(FeedbackSignal::CarSettingsChanged);
            }

            if (_immediateSignalCallback != nullptr)
            {
                _immediateSignalCallback(ImmediateSignal::CarSettingsChanged);
            }
        }
};
#endif
