#pragma once

#ifndef _MessageHandler_39B_2010_h
    #define _MessageHandler_39B_2010_h

#include <cstdint>

#include "../../../IMessageHandler.hpp"
#include "../../Structs/CAN_39B_2010.h"
#include "../../../FeedbackSignal.hpp"

class MessageHandler_39B_2010 : public IMessageHandler<MessageHandler_39B_2010>
{
    private:
        FeedbackSignalCallback _feedbackSignalCallback = nullptr;

        BusMessage message
        {
            .id = 0x39B,
            .command = 0,
            .data = {0},
            .dataLength = 8,
            .protocol = ProtocolType::AEE2010,
            .periodicityMs = 1000,
            .offsetMs = 130,
            .isActive = false
        };
    public:
        static constexpr uint32_t MessageId = 0x39B;

        void SetFeedbackSignalCallback(FeedbackSignalCallback feedbackSignalCallback) { _feedbackSignalCallback = feedbackSignalCallback; }

        BusMessage Generate(CarState* carState)
        {
            // this is generated by the NAC when the user sets the time via menu
            return message;
        }

        void Parse(CarState* carState, const BusMessage& message)
        {
            CAN_39B_2010_Byte1Struct byte1{};
            byte1.asByte = message.data[0];

            carState->Year = byte1.data.year + 2000;

            if (byte1.data.time_format != carState->TIME_FORMAT_24H)
            {
                carState->TIME_FORMAT_24H = byte1.data.time_format;
                carState->SAVE_CONFIG = true;
            }

            CAN_39B_2010_Byte2Struct byte2{};
            byte2.asByte = message.data[1];
            carState->Month = byte2.data.month;

            CAN_39B_2010_Byte3Struct byte3{};
            byte3.asByte = message.data[2];
            carState->MDay = byte3.data.day;

            CAN_39B_2010_Byte4Struct byte4{};
            byte4.asByte = message.data[3];
            carState->Hour = byte4.data.hour;

            CAN_39B_2010_Byte5Struct byte5{};
            byte5.asByte = message.data[4];
            carState->Minute = byte5.data.minute;

            if (_feedbackSignalCallback != nullptr)
            {
                _feedbackSignalCallback(FeedbackSignal::ClockSetByUser);
            }
        }
};
#endif
