#pragma once

#ifndef _MessageHandler_1E9_2010_h
    #define _MessageHandler_1E9_2010_h

#include <cstdint>
#include <cstring>

#include "../../../IMessageHandler.hpp"
#include "../../Structs/CAN_1E9_2010.h"
#include "../../../FeedbackSignal.hpp"

class MessageHandler_1E9_2010 : public IMessageHandler<MessageHandler_1E9_2010>
{
    private:
        FeedbackSignalCallback _feedbackSignalCallback = nullptr;

        BusMessage message
        {
            .id = 0x1E9,
            .command = 0,
            .data = {0},
            .dataLength = 6,
            .protocol = ProtocolType::AEE2010,
            .periodicityMs = 500,
            .offsetMs = 485,
            .isActive = false
        };
    public:
        static constexpr uint32_t MessageId = 0x1E9;

        void SetFeedbackSignalCallback(FeedbackSignalCallback feedbackSignalCallback) { _feedbackSignalCallback = feedbackSignalCallback; }

        BusMessage Generate(CarState* carState)
        {
            // this is generated by the NAC and it contains the speed limit from the NAC
            return message;
        }

        void Parse(CarState* carState, const BusMessage& message)
        {
            if (message.dataLength < 3)
            {
                carState->SpeedLimitFromNacAuthorized = false;
                carState->AdvisedSpeedFromNacInKmh = 0xFF;
                return;
            }

            CAN_1E9_2010_Struct packet;
            std::memcpy(&packet, message.data, sizeof(packet));

            carState->SpeedLimitFromNacAuthorized = packet.SpeedLimitStatus.data.speed_display_authorization == 1;
            if (carState->SpeedLimitFromNacAuthorized)
            {
                carState->AdvisedSpeedFromNacInKmh = packet.AdvisedSpeed;
                return;
            }

            carState->AdvisedSpeedFromNacInKmh = 0xFF;
        }
};
#endif
